# Generated by Django 6.0.1 on 2026-02-28 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_dispute_payout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20)),
                ('sampling_location', models.CharField(max_length=255)),
                ('soil_photo', models.ImageField(upload_to='ph_samples/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('booking_time', models.CharField(blank=True, max_length=50, null=True)),
                ('assigned_agent', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_requests', to='main_app.farmerprofile')),
            ],
        ),
    ]
