# Generated by Django 6.0.1 on 2026-03-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_phtestrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='land_area',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Land area in acres', max_digits=6),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
