# Generated by Django 6.0.1 on 2026-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_farmerprofile_bio_farmerprofile_land_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='next_subsidy_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
