# Generated by Django 6.0.1 on 2026-03-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_farmerprofile_next_subsidy_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
