# Generated by Django 6.0.1 on 2026-03-04 13:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_customerprofile_city_customerprofile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
