# Generated by Django 6.0.1 on 2026-04-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Kerala, India', max_length=255)),
                ('email', models.EmailField(default='support@efarming.com', max_length=254)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('working_hours', models.CharField(default='Mon-Sun: 7AM - 10PM', max_length=100)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
