# Generated by Django 6.0.1 on 2026-04-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='soil_ph_level',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
